language: generic

sudo: required

services: 
  - docker

before_install:
  - docker build -t ssunaa/docker-fullstack-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true ssunaa/docker-fullstack-app npm run test

after_success:
  - docker build -t ssunaa/docker-frontend ./frontend
  - docker build -t ssunaa/docker-backend ./backend
  - docker build -t ssunaa/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push ssunaa/docker-frontend
  - docker push ssunaa/docker-backend
  - docker push ssunaa/docker-nginx